[package]
name = "biosim-rust-shader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { version = "0.9" }
libm = "0.2"
biosim-core = { path = "../biosim-core"}

[features]
rect_grid = []
